version: "3.8"
services:
  frontend:
    build: ./FlixPicks-Front
    ports:
      - 80:2000
    environment:
      DB_URL: http://database:3000/api
  database:
    build: ./FlixPicks-DB
    ports:
      - 3000:3000
    environment:
      DB_URL: http://database:3000/api